name: CI/CD

on:
  push:
    branches: [main, master]  # This pipeline runs when there is a push to the main or master branch
  workflow_dispatch:  ## This pipeline can be invoked manually from the Actions tab on GitHub

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Replace with your Node.js version if needed

      # Install npm dependencies (including testing libraries like Mocha, Chai)
      - name: Install dependencies
        run: npm install

      # Run the tests
      - name: Run Tests
        run: npm test  # Run the tests, assuming you have a test script in package.json

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node_dictionary_app:latest