name: CI/CD

# Controls when the workflow will run
on:
  # Activates the workflow; then there is a push to the main or master branch
  push:
    branches: [main, master]

  # allows you to manually execute this pipeline from the Actions tab.
  workflow_dispatch:
env:
# A workflow run consists of one or more jobs that can be executed either sequentially or concurrently.
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    #
    steps:
      - uses: actions/checkout@v2 # checkout the code 
      - uses: actions/setup-node@v4 # sets up setup-node@v2
      - run: npm i  # install required packages

      - name: Log in to Docker Hub # docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # fill in username
          password: ${{ secrets.DOCKERHUB_TOKEN }} # fill in password

      # - name: Push Docker Image # push docker image to a registry
      #   run: docker push my-app.:${{ github.sha }} # might need a fix

        name: Deploy
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/node_dictionary_app:latest
      
              
