name: CI/CD

on:
  push:
    branches: [main, master] # This pipeline runs when there is a push to the main or master branch

 
  workflow_dispatch:  ## This pipeline can be invoked manually from the Actions tab on GitHub
env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    #
    steps:
      - uses: actions/checkout@v2 # Check out the code repo
      - uses: actions/setup-python@v2 # sets up python@v2
      - run: npm i  # Install necessary packages

      - name: Log in to Docker Hub # docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node_dictionary_app:latest
